# 基於的映像檔
FROM alpine:latest

# 建立工作目錄
WORKDIR /usr/src/app

# 時區
ENV TZ=Asia/Taipei
RUN echo "${TZ}" > /etc/timezone 
RUN ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime 

# 安裝&更新所需的套件
RUN apk update
RUN apk upgrade --no-cache
RUN apk add --no-cache nodejs npm icu-data-full tzdata
RUN rm /var/cache/apk/*

# 把目錄下的程式碼直接復制到容器中
COPY package*.json ./
RUN npm install 
COPY . .

# 指定使用的端口
EXPOSE 5000

# 容器啟動時
CMD [ "npm", "start" ]